title: Ming Zhang
author: Ming Zhang
favicon: /img/favicon-32x32.png
email: hello@mingzhang.me
copyright_name: Ming Zhang
description: "Ming Zhang is a sophomore at University of Pennsylvania studying computer science and linguistics."
baseurl: ""
url: "http://mingzhang.me"
twitter_username: mingypoo
github_username:  ming-zhang
# facebook_username:  StartBootstrap
linkedin_username: mingzhang2019

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-57191041-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
